# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/870/bin/cmake

# The command to remove a file.
RM = /snap/cmake/870/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/christopher/versioned/disease-simulations

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/christopher/versioned/disease-simulations

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/870/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/870/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christopher/versioned/disease-simulations/CMakeFiles /home/christopher/versioned/disease-simulations//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christopher/versioned/disease-simulations/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named disease_simulations

# Build rule for target.
disease_simulations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 disease_simulations
.PHONY : disease_simulations

# fast build rule for target.
disease_simulations/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/build
.PHONY : disease_simulations/fast

code/main/src/main.o: code/main/src/main.cpp.o
.PHONY : code/main/src/main.o

# target to build an object file
code/main/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/main.cpp.o
.PHONY : code/main/src/main.cpp.o

code/main/src/main.i: code/main/src/main.cpp.i
.PHONY : code/main/src/main.i

# target to preprocess a source file
code/main/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/main.cpp.i
.PHONY : code/main/src/main.cpp.i

code/main/src/main.s: code/main/src/main.cpp.s
.PHONY : code/main/src/main.s

# target to generate assembly for a file
code/main/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/main.cpp.s
.PHONY : code/main/src/main.cpp.s

code/main/src/math/InfectionSpreadCalculator.o: code/main/src/math/InfectionSpreadCalculator.cpp.o
.PHONY : code/main/src/math/InfectionSpreadCalculator.o

# target to build an object file
code/main/src/math/InfectionSpreadCalculator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/math/InfectionSpreadCalculator.cpp.o
.PHONY : code/main/src/math/InfectionSpreadCalculator.cpp.o

code/main/src/math/InfectionSpreadCalculator.i: code/main/src/math/InfectionSpreadCalculator.cpp.i
.PHONY : code/main/src/math/InfectionSpreadCalculator.i

# target to preprocess a source file
code/main/src/math/InfectionSpreadCalculator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/math/InfectionSpreadCalculator.cpp.i
.PHONY : code/main/src/math/InfectionSpreadCalculator.cpp.i

code/main/src/math/InfectionSpreadCalculator.s: code/main/src/math/InfectionSpreadCalculator.cpp.s
.PHONY : code/main/src/math/InfectionSpreadCalculator.s

# target to generate assembly for a file
code/main/src/math/InfectionSpreadCalculator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/math/InfectionSpreadCalculator.cpp.s
.PHONY : code/main/src/math/InfectionSpreadCalculator.cpp.s

code/main/src/math/utils/MathematicalUtils.o: code/main/src/math/utils/MathematicalUtils.cpp.o
.PHONY : code/main/src/math/utils/MathematicalUtils.o

# target to build an object file
code/main/src/math/utils/MathematicalUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/math/utils/MathematicalUtils.cpp.o
.PHONY : code/main/src/math/utils/MathematicalUtils.cpp.o

code/main/src/math/utils/MathematicalUtils.i: code/main/src/math/utils/MathematicalUtils.cpp.i
.PHONY : code/main/src/math/utils/MathematicalUtils.i

# target to preprocess a source file
code/main/src/math/utils/MathematicalUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/math/utils/MathematicalUtils.cpp.i
.PHONY : code/main/src/math/utils/MathematicalUtils.cpp.i

code/main/src/math/utils/MathematicalUtils.s: code/main/src/math/utils/MathematicalUtils.cpp.s
.PHONY : code/main/src/math/utils/MathematicalUtils.s

# target to generate assembly for a file
code/main/src/math/utils/MathematicalUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/math/utils/MathematicalUtils.cpp.s
.PHONY : code/main/src/math/utils/MathematicalUtils.cpp.s

code/main/src/simulations/RandomWalkSimulation.o: code/main/src/simulations/RandomWalkSimulation.cpp.o
.PHONY : code/main/src/simulations/RandomWalkSimulation.o

# target to build an object file
code/main/src/simulations/RandomWalkSimulation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/simulations/RandomWalkSimulation.cpp.o
.PHONY : code/main/src/simulations/RandomWalkSimulation.cpp.o

code/main/src/simulations/RandomWalkSimulation.i: code/main/src/simulations/RandomWalkSimulation.cpp.i
.PHONY : code/main/src/simulations/RandomWalkSimulation.i

# target to preprocess a source file
code/main/src/simulations/RandomWalkSimulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/simulations/RandomWalkSimulation.cpp.i
.PHONY : code/main/src/simulations/RandomWalkSimulation.cpp.i

code/main/src/simulations/RandomWalkSimulation.s: code/main/src/simulations/RandomWalkSimulation.cpp.s
.PHONY : code/main/src/simulations/RandomWalkSimulation.s

# target to generate assembly for a file
code/main/src/simulations/RandomWalkSimulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/simulations/RandomWalkSimulation.cpp.s
.PHONY : code/main/src/simulations/RandomWalkSimulation.cpp.s

code/main/src/subjectData/HealthStatus.o: code/main/src/subjectData/HealthStatus.cpp.o
.PHONY : code/main/src/subjectData/HealthStatus.o

# target to build an object file
code/main/src/subjectData/HealthStatus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/subjectData/HealthStatus.cpp.o
.PHONY : code/main/src/subjectData/HealthStatus.cpp.o

code/main/src/subjectData/HealthStatus.i: code/main/src/subjectData/HealthStatus.cpp.i
.PHONY : code/main/src/subjectData/HealthStatus.i

# target to preprocess a source file
code/main/src/subjectData/HealthStatus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/subjectData/HealthStatus.cpp.i
.PHONY : code/main/src/subjectData/HealthStatus.cpp.i

code/main/src/subjectData/HealthStatus.s: code/main/src/subjectData/HealthStatus.cpp.s
.PHONY : code/main/src/subjectData/HealthStatus.s

# target to generate assembly for a file
code/main/src/subjectData/HealthStatus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/subjectData/HealthStatus.cpp.s
.PHONY : code/main/src/subjectData/HealthStatus.cpp.s

code/main/src/subjectData/Location.o: code/main/src/subjectData/Location.cpp.o
.PHONY : code/main/src/subjectData/Location.o

# target to build an object file
code/main/src/subjectData/Location.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/subjectData/Location.cpp.o
.PHONY : code/main/src/subjectData/Location.cpp.o

code/main/src/subjectData/Location.i: code/main/src/subjectData/Location.cpp.i
.PHONY : code/main/src/subjectData/Location.i

# target to preprocess a source file
code/main/src/subjectData/Location.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/subjectData/Location.cpp.i
.PHONY : code/main/src/subjectData/Location.cpp.i

code/main/src/subjectData/Location.s: code/main/src/subjectData/Location.cpp.s
.PHONY : code/main/src/subjectData/Location.s

# target to generate assembly for a file
code/main/src/subjectData/Location.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/subjectData/Location.cpp.s
.PHONY : code/main/src/subjectData/Location.cpp.s

code/main/src/subjectData/Subject.o: code/main/src/subjectData/Subject.cpp.o
.PHONY : code/main/src/subjectData/Subject.o

# target to build an object file
code/main/src/subjectData/Subject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/subjectData/Subject.cpp.o
.PHONY : code/main/src/subjectData/Subject.cpp.o

code/main/src/subjectData/Subject.i: code/main/src/subjectData/Subject.cpp.i
.PHONY : code/main/src/subjectData/Subject.i

# target to preprocess a source file
code/main/src/subjectData/Subject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/subjectData/Subject.cpp.i
.PHONY : code/main/src/subjectData/Subject.cpp.i

code/main/src/subjectData/Subject.s: code/main/src/subjectData/Subject.cpp.s
.PHONY : code/main/src/subjectData/Subject.s

# target to generate assembly for a file
code/main/src/subjectData/Subject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/subjectData/Subject.cpp.s
.PHONY : code/main/src/subjectData/Subject.cpp.s

code/main/src/utils/GridUtils.o: code/main/src/utils/GridUtils.cpp.o
.PHONY : code/main/src/utils/GridUtils.o

# target to build an object file
code/main/src/utils/GridUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/utils/GridUtils.cpp.o
.PHONY : code/main/src/utils/GridUtils.cpp.o

code/main/src/utils/GridUtils.i: code/main/src/utils/GridUtils.cpp.i
.PHONY : code/main/src/utils/GridUtils.i

# target to preprocess a source file
code/main/src/utils/GridUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/utils/GridUtils.cpp.i
.PHONY : code/main/src/utils/GridUtils.cpp.i

code/main/src/utils/GridUtils.s: code/main/src/utils/GridUtils.cpp.s
.PHONY : code/main/src/utils/GridUtils.s

# target to generate assembly for a file
code/main/src/utils/GridUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disease_simulations.dir/build.make CMakeFiles/disease_simulations.dir/code/main/src/utils/GridUtils.cpp.s
.PHONY : code/main/src/utils/GridUtils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... disease_simulations"
	@echo "... code/main/src/main.o"
	@echo "... code/main/src/main.i"
	@echo "... code/main/src/main.s"
	@echo "... code/main/src/math/InfectionSpreadCalculator.o"
	@echo "... code/main/src/math/InfectionSpreadCalculator.i"
	@echo "... code/main/src/math/InfectionSpreadCalculator.s"
	@echo "... code/main/src/math/utils/MathematicalUtils.o"
	@echo "... code/main/src/math/utils/MathematicalUtils.i"
	@echo "... code/main/src/math/utils/MathematicalUtils.s"
	@echo "... code/main/src/simulations/RandomWalkSimulation.o"
	@echo "... code/main/src/simulations/RandomWalkSimulation.i"
	@echo "... code/main/src/simulations/RandomWalkSimulation.s"
	@echo "... code/main/src/subjectData/HealthStatus.o"
	@echo "... code/main/src/subjectData/HealthStatus.i"
	@echo "... code/main/src/subjectData/HealthStatus.s"
	@echo "... code/main/src/subjectData/Location.o"
	@echo "... code/main/src/subjectData/Location.i"
	@echo "... code/main/src/subjectData/Location.s"
	@echo "... code/main/src/subjectData/Subject.o"
	@echo "... code/main/src/subjectData/Subject.i"
	@echo "... code/main/src/subjectData/Subject.s"
	@echo "... code/main/src/utils/GridUtils.o"
	@echo "... code/main/src/utils/GridUtils.i"
	@echo "... code/main/src/utils/GridUtils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

